### ISSUE TITLE
An option to 'hide and  update another' button

### ISSUE THREAD

**Issue by vickey98** [gigcodes/vue-admin-panel#2]
<img width="365" alt="Screenshot 2022-02-20 at 7 24 22 PM" src="https://user-images.githubusercontent.com/73880633/154846029-5cdf5f71-9c41-40a9-bf46-4a12225c8b6b.png">

**Comment by kkz6** [comment]
hasContinue,
hasAddAnother

props added. So based the props passes the buttons will be visible. Both are default set to tru
